### ISSUE TITLE
[BUG] - Giga Stations Index out of Bounds

### ISSUE THREAD

**Issue by Ferlonas** [limoka/DSP-Mods#107]
**Describe the bug**
Error message pops up, first time it prevented deliveries from the affected station, now I can't be sure (too many stations to check each individually)

**To Reproduce**
It just happens, but reliably. ~~It might be interference from another mod, but I have not isolated it yet.~~ I deactivated all mods but Giga Stations and its dependencies, still happens.
First time it happened when I added more than 10 ships to a giga station. Then I reduced the ship limit for new stations and everything was fine for a while. Now it happens and I don't know why
I've got a save file in which it reliably happens after a minute, if that helps. Until I find the cause, this prevents me from continuing with the game unfortunately.
Edit: Seems the culprit this time are Giga Orbital Collectors. However, I do not have time to remove them all before the error starts, and once it starts, it persists even after removing the mod.

**Log files**
[LogOutput.log](https://github.com/user-attachments/files/16623341/LogOutput.log)

**Screenshots**
![Screenshot 2024-08-15 103841](https://github.com/user-attachments/assets/ac0d6cb6-7f08-47d6-a518-68150a91547c)

**Additional context**
Profile code: 0191554d-11e6-f0aa-9ed1-de3995816f41
Profile code with only giga stations: 01915568-b2af-ce94-a985-025687f2e56a

**Comment by Ferlonas** [comment]
Addendum: Deleting the mod right away causes the bug count to rise very quickly, as suddenly the stations are not there anymore. I therefore make the assumption that it is not the error causing the deliveries to not occur anymore, but instead the stations become unregistered, which means when the game attempts to address them, it can not find them.
This is wild speculation on my part though.

**Comment by Maga-sword** [comment]
So I am having this problem too. It only happens when I am specifically drawing fireice. Hydrogen works perfectly just fireice makes it bug out. I don't have a deutritium giants so I can't test it on those sadly.

**Comment by raziel29a** [comment]
> Addendum: Deleting the mod right away causes the bug count to rise very quickly, as suddenly the stations are not there anymore. I therefore make the assumption that it is not the error causing the deliveries to not occur anymore, but instead the stations become unregistered, which means when the game attempts to address them, it can not find them. This is wild speculation on my part though.
> 
> Addendum 2: Identifying and deconstructing all affected stations stops the error message and allows the save to work properly again in the future.

How to identify the affected stations?

**Comment by limoka** [comment]
Hello everyone, thanks for reporting. I was extremely busy over last month with the release of Core Keeper 1.0 update. I will try to release an update soon.

**Comment by limoka** [comment]
I have a request to original issue submitter and anyone else experiencing this issue: can you please provide a save on which said error occurs, so I can more easily reproduce and fix the issue.

**Comment by limoka** [comment]
This issue should be resolved in v2.3.8. If you encounter other issues, open new issues

**Comment by Ferlonas** [comment]
Thank you very much. I'm looking forward to using Giga Stations again :-)
